name: run-tests
on:
  push:
    branches:
      - "**"
    tags:
      - "**"

jobs:
  run-tests:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - uses: astral-sh/setup-uv@2ddd2b9cb38ad8efd50337e8ab201519a34c9f24 # v7.1.1
      - name: ruff format-check
        run: |
          uv run ruff format --check
      - name: run-tests
        run: |
          ./run-tests.sh
